from app.models import db, Recipe

def seed_recipes():
    r1 = Recipe(
        user_id='1', title='Birria Tacos', image_url='https://www.simplyrecipes.com/thmb/McnGMrSn8QZGQI-CPukkSllZgu8=/720x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Birria-Tacos-LEAD-07-800cb0c73bdb4d32acfec9853ae2ed35.jpg', category_id='3', directions="1. Reheat 4 cups of consome. Once it comes up to a boil, lower the heat to a simmer and keep the lid on. \n 2. In a large frying pan set over medium heat, heat 1 tablespoon olive oil. When the oil is hot and rippling, but not smoking, dip a tortilla into the consomé, covering both sides with it. Fill the tortilla with 2 tablespoons birria meat and 1 tablespoon cheese. Transfer it into the hot pan, don’t fold it in half yet. Once the bottom of the tortilla turns lightly golden brown, fold it in half. Cook both sides until the cheese is melted and the tortillas are a deeper golden brown. Cook 2 to 3 tacos at a time following this process and adding more oil to the pan, as needed. \n 3. Transfer the tacos onto a plate and serve with the onions and cilantro scattered on top and lime wedges on the side. Provide each guest with a small bowl of warm consomé for dipping. Enjoy!The best birria tacos are freshly made, but leftover tacos and consomé can be tightly covered and refrigerated, separately, for up to 3 days. To reheat, simply place the tacos on a pan over medium-low heat and cover with a lid. Warm them up for 2 to 3 minutes on each side. Reheat the consomé separately in a small saucepan. "
    )
    r2 = Recipe(
        user_id='1', title='Easy Crispy Tofu', image_url='https://www.simplyrecipes.com/thmb/R6Z9l85DmSzgk_MXh4K_bvgymws=/648x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Crispy-Tofu-LEAD-07-f828d15f6bba43c18edab27d8bf69059.jpg', category_id='7', directions="1. Line the bottom of a 9 x 5-inch loaf pan with 4 or 5 paper towels or a folded, clean kitchen towel. Place the tofu on top, centered in the pan. Top it with another stack of paper towels or kitchen towel. Nestle in a second loaf pan so it sits right on top of the towel-covered tofu. Fill the top pan with 3 canned goods or any heavy items that’ll fit. Let sit for 30 minutes or up to an hour. The towels should be saturated, and the tofu should feel much drier to the touch. \n 2. Arrange a rack in the center of the oven and preheat it to 425°F. Line a baking sheet with parchment paper or a silicone mat and spray it generously with cooking spray. \n 3. In a medium bowl, add the soy sauce, vegetable oil, sesame oil, rice vinegar, and sugar. Whisk together with a fork or small whisk until the sugar is dissolved, about 30 seconds. In a small bowl, combine the cornstarch, breadcrumbs, salt, and black pepper and mix. Set both bowls aside. \n 4. Remove the tofu from the press and place it on a cutting board. Set the tofu up on its longest side and slice it lengthwise into 2 thin rectangles. Lay them flat on top of each other and make 3 equal cuts lengthwise followed by 2 cuts crosswise, making 24 equal cubes. \n 5. Add the cubed tofu into the marinade and use a rubber spatula or large wooden spoon to gently toss them to evenly coat. Be careful not to break up the tofu. It’s okay if there’s a little marinade left in in the bowl. \n 6. Add the breading over the marinated tofu and toss gently but thoroughly, coating the cubes on all sides. You might have some crumbs stuck to the bowl; you can discard them or toast them in a small pan to serve on top of the crispy tofu. \n 7. Scatter the tofu on the prepared baking sheet an inch or so apart from each other. Spray the tops generously with cooking spray. Bake until the tofu is browned and crispy, 20 to 25 minutes. Serve warm. Refrigerate leftovers for up to 4 days. I don’t recommend freezing crispy tofu. Reheat in a nonstick pan over medium heat with a little oil or in a 350°F oven until warmed through."
    )

    db.session.add_all([r1, r2])

    db.session.commit()

def undo_recipes():
    db.session.execute('TRUNCATE recipes RESTART IDENTITY CASCADE;')
    db.session.commit()
