"""empty message

Revision ID: 65180552f8ab
Revises: 1a6eba5a3efc
Create Date: 2022-05-19 14:07:05.408094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65180552f8ab'
down_revision = '1a6eba5a3efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('image_url', sa.VARCHAR(length=5000), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
