"""empty message

Revision ID: 43f8af2f1148
Revises: dddb6a621475
Create Date: 2022-05-12 10:56:40.215402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f8af2f1148'
down_revision = 'dddb6a621475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('prep_time', sa.String(), nullable=False))
    op.add_column('recipes', sa.Column('cook_time', sa.String(), nullable=False))
    op.add_column('recipes', sa.Column('total_time', sa.String(), nullable=False))
    op.add_column('recipes', sa.Column('servings', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'servings')
    op.drop_column('recipes', 'total_time')
    op.drop_column('recipes', 'cook_time')
    op.drop_column('recipes', 'prep_time')
    # ### end Alembic commands ###
