"""empty message

Revision ID: d1d0e81383eb
Revises: 65180552f8ab
Create Date: 2022-06-13 13:20:04.659113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d0e81383eb'
down_revision = '65180552f8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image_url',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image_url',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    # ### end Alembic commands ###
