"""empty message

Revision ID: 1a6eba5a3efc
Revises: 80fb789a187e
Create Date: 2022-05-13 10:42:51.144429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6eba5a3efc'
down_revision = '80fb789a187e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image_url',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    op.alter_column('recipes', 'directions',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'directions',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('recipes', 'image_url',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    # ### end Alembic commands ###
