"""empty message

Revision ID: 80fb789a187e
Revises: 697acdd5917f
Create Date: 2022-05-12 15:46:43.016756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fb789a187e'
down_revision = '697acdd5917f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('categories', 'name')
    op.add_column('ingredient', sa.Column('title', sa.String(length=100), nullable=False))
    op.drop_column('ingredient', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('ingredient', 'title')
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('categories', 'title')
    # ### end Alembic commands ###
